# Use the standard Microsoft .NET Core container
FROM microsoft/dotnet
 
# Copy our code from the "/src/MyWebApi" folder to the "/app" folder in our container
WORKDIR /app
COPY ./business ./business
COPY ./common ./common
COPY ./data ./data
COPY ./api ./api
 
# Expose port 80 for the Web API traffic
ENV ASPNETCORE_URLS http://*:5000
EXPOSE 5000
# Restore the necessary packages
RUN cd api && dotnet restore
RUN cd api && dotnet build
RUN cd api && dotnet publish --configuration Release --output ./publish

COPY ./api/publish .
RUN cd publish
 
# Build and run the dotnet application from within the container
ENTRYPOINT ["dotnet", "api.dll"]